### ISSUE TITLE
[Epic] Synchronous off-chain EIP-1271 signature flow

### ISSUE THREAD

**Issue by schmanu** [safe-global/safe-wallet-web#1886]
### The Problem
Currently Safe{Wallet} supports two ways to sign a message (e.g. EIP-712).
1. on-chain by sending a transaction to the SignMessageLib smart contract.
2. using a separate off-chain flow which requires dapps to integrate with out transaction service.

Option 1) requires users to pay gas and does not work with all dapps as dapps expect the returned signature from e.g. `eth_signTypedData` to be valid (immediately).

Option 2) is gasless but requires dapps to built custom integrations with Safe{Wallet} which most dapps are not willing to do.

### The solution
We want to bring EIP-1271 in a way that it will work in most if not all dapps out of the box. 

The idea is that the first signer of any message will have to keep the Safe App & modal open until all signers signed it. Then the `preparedSignature` will be send as answer to the signature request.

We already evaluated the solution by building a PoC in this PR: #1630 
And tried it with multiple dapps. 

## The list of requirements
- [x] Technical realization of flow: https://github.com/safe-global/web-core/pull/1874
- [x] #1943
- [x] https://github.com/safe-global/web-core/issues/1887
- [ ] (optional) Add message signing to mobile apps
  - [ ] Android issue (tbd)
  - [ ] IOS issue (tbd) 
- [x] Update safe-apps-sdk: https://github.com/safe-global/safe-apps-sdk/pull/458 (Return signatures in SafeProvider)
- [x] Update WC Safe app: https://github.com/safe-global/safe-react-apps/pull/657 (Update safe-apps-sdk in WalletConnect app)

## Designs/sketches
[Figma](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?type=design&node-id=4901-108580&t=gj7PAEkxDjCxEdcm-0)

## Links
- [Notion page](https://www.notion.so/safe-global/Synchronous-off-chain-message-signatures-EIP-1271-9f16173cf12c472db189cbcbf54cbe28)

**Comment by McCloudS** [comment]
Maybe i'm still a bit premature, but building it safe wallet and WC (and also using the dev links), it fails trying to sign a message on OpenSea with seemingly random owner addresses.  This is on a 2/3 Multisig, the error occurs after the first sign.
![image](https://user-images.githubusercontent.com/64094529/236609217-070a44ff-9d77-4637-b6c7-5abe7076771b.png)

**Comment by schmanu** [comment]
@McCloudS What connected wallet are you using? 
Also which version is your deployed Safe (You can check that in `Settings -> Setup`)

**Comment by McCloudS** [comment]
Using Ledger via Metamask, since Ledgers don't support the v3/v4 signing and failed.  1.3.0 is deployed.

**Comment by schmanu** [comment]
@McCloudS we found the issue and it will be fixed with this PR: https://github.com/safe-global/safe-wallet-web/pull/1958
