### ISSUE TITLE
Epic: [Seedless-Onboarding]

### ISSUE THREAD

**Issue by schmanu** [safe-global/safe-wallet-web#2452]
## What is the feature about
We want to integrate a solution for seedless onboarding by logging in through an social account.

This is the epic issue. Separate issues will be created for each requirement / user story.

## The list of requirements
- [ ] Integrate authenticators
  - [x] Google
  - [ ] (optional) #2457 v2
- [x] Device share
  - [x] Store device share in local storage
- [ ] Recovery
  - [x] #2455 
  - [ ] (optional) #2486 v2
  - [x] Build Single factor recovery
- [x] Wallet integration
  - [x] #2456
- [x] Blockchain interactions (are done via Provider, should work once the Web3Provider can be created)
  - The returned provider does not correctly implement `eth_estimateGas`, we had to patch it's `eth_estimateGas` method to call the readonly provider's `eth_estimateGas` method. 
  - [x] Sign messages
  - [x] Sign transactions
- [ ] Implement designs / user flows
  - [x] #2459
  - [x] #2569
  - [x] New quick Safe creation flow
  - [x] Update Account center
  - [ ] (optional) Add global MFA prompt
  - [x] #2589
  - [x] #2519
- [x] #2458

## Designs/sketches
tbd

## Links
https://www.notion.so/safe-global/Feature-spec-d4b73908e0804f22b9c92565ec8f98c0

**Comment by francovenica** [comment]
This epic has been tested and the tickets with issues were cleared from the board in notion. So this feature is ready to be put into an RC. I'll pass it to done.

The task marked as optional will be tackled in the next iteration
